### ISSUE TITLE
Semver

### ISSUE THREAD

**Issue by qrnch-jan** [fprasx/effect-cell#4]
I saw that @ScratchCat458's PR was merged -- very happy to see that.

However, it contains API breaking changes (see `new()` method) but the published version was bumped from `0.1.0` to `0.1.1`, which is not [semver compliant](https://doc.rust-lang.org/cargo/reference/resolver.html#semver-compatibility).

Please consider being semver compatible in the future -- it makes life easier for us downstream users of your crate.

I figure this was just an oversight, but I wanted to mention it just in case.

**Comment by HaydenAtFoxHaven** [comment]
Good point and apologies! I haven't read up on SemVer in a while and probably should have checked prior to the push. 
I agree that we should more strictly follow it in future, especially considering the way cargo matches version numbers.
